#ifndef MESSAGEBOX_GLOBAL_H
#define MESSAGEBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSAGEBOX_LIBRARY)
#  define MESSAGEBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGEBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSAGEBOX_GLOBAL_H
